### ISSUE TITLE
Issue going to project list screen

### ISSUE THREAD

**Issue by gmercede** [Acumatica/Acumatica-Smartsheet#2]
See trace:

Error: | Error: You don't have enough rights on 'Select'. | Send
-- | -- | --
  | Raised At: 11/6/2017 2:48:54 PM | Screen: PM.30.10.00 |   |  
Details: 11/6/2017 2:48:54 PM Error: Error: You don't have enough rights on 'Select'.    at PX.Data.PXSetup`1.a()    at PX.Data.PXGraph.GetDefault[TNode]()    at PX.Data.PXCache`1.get_Current()    at PX.Data.PXSelectBase`1.get_Current()    at PX.Objects.PM.ProjectEntry..ctor()    at PX.Data.PXGraph.CreateInstance(Type graphType, String prefix)    at PX.Web.UI.PXBaseDataSource.f(Type A_0)    at PX.Web.UI.PXBaseDataSource.g(Type A_0)    at PX.Web.UI.PXBaseDataSource.get_DataGraph()    at PX.Web.UI.PXDataSourceView..ctor(PXBaseDataSource owner, String viewName)    at PX.Web.UI.PXBaseDataSource.GetView(String viewName)    at PX.Web.UI.PXFormDataProvider.GetDataView()    at PX.Web.UI.PXBoundPanel.SynchronizeState(Boolean dataBinding, Boolean preserveValue)    at PX.Web.UI.PXBoundPanel.CreateChildControls()    at System.Web.UI.Control.EnsureChildControls()    at System.Web.UI.WebControls.CompositeDataBoundControl.get_Controls()    at PX.Web.UI.PXSmartPanel.a(ControlCollection A_0, Boolean A_1, Boolean A_2)    at PX.Web.UI.PXSmartPanel.a(Boolean A_0)    at PX.Web.UI.PXSmartPanel.SetBindingState(Boolean load)    at PX.Web.UI.PXSmartPanel.OnInit(EventArgs e)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Control.InitRecursive(Control namingContainer)    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

From redirect:

Information: | Redirect0:/cloud9erp/(W(1))/pages/pm/pm301000.aspx | Send
-- | -- | --
  | Raised At: 11/6/2017 2:48:15 PM | Screen: 00.00.00.00 | Command: ReloadPage |  
Details: 11/6/2017 2:48:15 PM Information: Redirect0:/cloud9erp/(W(1))/pages/pm/pm301000.aspx    at PX.Web.UI.PXBaseDataSource.RedirectHelper.a(PXRedirectToUrlException A_0)    at PX.Web.UI.PXBaseDataSource.RedirectHelper.TryRedirect(PXBaseRedirectException data)    at PX.Web.UI.PXBaseDataSource.ExecuteSelect(String viewName, DataSourceSelectArguments arguments, PXDSSelectArguments pxarguments)    at PX.Web.UI.PXDataSource.ExecuteSelect(String viewName, DataSourceSelectArguments arguments, PXDSSelectArguments pxarguments)    at PX.Web.UI.PXGenericDataSource.ExecuteSelect(String viewName, DataSourceSelectArguments arguments, PXDSSelectArguments pxarguments)    at PX.Web.UI.PXDataSourceView.Select(DataSourceSelectArguments arguments, PXDSSelectArguments swarguments, DataSourceViewSelectCallback callback)    at PX.Web.UI.PXGrid.PerformSelect()    at System.Web.UI.WebControls.BaseDataBoundControl.EnsureDataBound()    at PX.Web.UI.PXGrid.PX.Web.UI.IPXDataBoundControl.EnsureDataBoundInternal()    at PX.Web.UI.PXCallbackManager.a(Dictionary`2 A_0, List`1 A_1)    at PX.Web.UI.PXCallbackManager.a(PXCallbackResultMethod A_0, XmlWriter A_1)    at PX.Web.UI.PXCallbackManager.a(PXCallbackResultMethod A_0)

**Comment by gmercede** [comment]
Hmm, well you have the post.  But it worked after I closed my browser and opened back again.  It did take a long time to return results from the Project List GI, I'll report back if I see anything else fishy

**Comment by DhirenChhapgar** [comment]
Project List GI is not affected by this Extension.
