### ISSUE TITLE
User Profile, Get SmartSheet Token, returns The Client ID is missing or invalid

### ISSUE THREAD

**Issue by gmercede** [Acumatica/Acumatica-Smartsheet#3]
I've configured the Project Preference ID and secret.

When I go to user profile and click Get SmartSheet Token, I get The Client ID is missing or invalid.

![smartsheet issue](https://user-images.githubusercontent.com/31712032/32463567-37ac4b28-c30b-11e7-92cb-29944282d810.png)

**Comment by DhirenChhapgar** [comment]
Issue is resolved.
