### ISSUE TITLE
Got error when work with Acumatica 2020 R2 Build 20.201.0051 

### ISSUE THREAD

**Issue by kma77** [Acumatica/Acumatica-Smartsheet#5]
Using the latest smart sheet code against  Acumatica 2020 R2 Build 20.201.0051， and after clicking get token and click allow in the pop up window, it gives error as below
![image](https://user-images.githubusercontent.com/35674418/99473799-2ebc3000-29b0-11eb-8f80-ed30c9c76240.png)

Is current smartsheet integration works with this version acumatica?

**Comment by pwills0926** [comment]
Similar issue after publishing customization when user attempts to login. Acumatica 2020 R1 Build 20.109.0032
![Capture](https://user-images.githubusercontent.com/74780247/99811580-5b3c8d00-2b13-11eb-80f7-824fc07f12bc.JPG)

**Comment by famadoz** [comment]
@kma77 I am unable to reproduce the error in a QA environment.
Would you have time to meet via Zoom some time this week?

**Comment by pwills0926** [comment]
Yes I’m available tomorrow, anytime. Just let me know what works for you. 

 

 

 

 




Patrick Wills

Senior Consultant | ACC Software Solutions

 

535 Route 38, Suite 320, Cherry Hill, NJ 08002

856.335.1010 x103


 <https://www.linkedin.com/company-beta/1102619>  <https://twitter.com/ACC_Software>  <https://www.facebook.com/ACCsoftwaresolutions/>  <https://www.instagram.com/accsoftware/>  <http://www.youtube.com/c/4accAccountingSolutions> 

 

 <mailto:pwills@4acc.com> pwills@4acc.com

**Comment by famadoz** [comment]
@pwills0926 I will contact you via email

**Comment by kma77** [comment]
@famadoz  Sure please let me know a time, i should be available most time this week, please send me a meeting invite a day ahead, thanks. By the way i am using MySql database, do you think that matters.

**Comment by kma77** [comment]
@famadoz Can you please let me know what is a good time for a screen share session, thanks

**Comment by famadoz** [comment]
@kma77 could you please share your email address to contact you over there? Thanks.

**Comment by kma77** [comment]
> @kma77 could you please share your email address to contact you over there? Thanks.

@famadoz kevin.ma@myob.com

**Comment by famadoz** [comment]
Updated package that addresses this error is available in GitHub
