### ISSUE TITLE
2020R1 - Referenced field missing: action from PX.Objects.PM.ProjectEntry

### ISSUE THREAD

**Issue by GrahamTheHat** [Acumatica/Acumatica-Smartsheet#7]
Hi all,

Couple of things - initial attempt to install required unpacking of the repository download to get access to the ZIP with the project.xml file in it appropriate to my version (just a comment that one as the existing instructions don't mention that step).

Second, on upgrading to 2020R1 and attempting to re-publish the customisation it failed. It passes the Validate check, but then at the "Validating Binary Files" stage it fails with:-

Referenced field missing: action from PX.Objects.PM.ProjectEntry

smartsheet-csharp-sdk.dll Failed to resolve type reference: RestSharp.Extensions.MonoHttp.HttpUtility declared in RestSharp, Version=100.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75

smartsheet-csharp-sdk.dll Failed to resolve method reference: System.String RestSharp.Extensions.MonoHttp.HttpUtility::UrlEncode(System.String,System.Text.Encoding) declared in RestSharp, Version=100.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75

Validation failed.

I don't have the skill to fix this, so wondered who is the right person to ask to look at it?

Thank you for your anticipated help, my best regards,
Graham

_Screen shot of issue when following install instructions (more a comment than a bug report):-_

![SMARTSheetCommect1](https://user-images.githubusercontent.com/49095350/116096259-0ba15500-a6a1-11eb-8bf9-98ff47fff518.png)

_Actual bug when attempting to re-publish or even install from scratch on 2021R1 ..._

[SMARTSheetBug2.txt](https://github.com/Acumatica/Acumatica-Smartsheet/files/6377712/SMARTSheetBug2.txt)

**Comment by famadoz** [comment]
Hi @GrahamTheHat 
It is not clear if you are trying to publish on 2020R1 or 2021R1.
If it's the latter, a compatible version for 21R1 was published earlier today. 
Please download it from [this](https://github.com/Acumatica/Acumatica-Smartsheet/raw/master/AcumaticaSmartsheetIntegration21R1.zip) link in the repository

**Comment by GrahamTheHat** [comment]
My many apologies @famadoz - I made a typo.

Apologies again for confusion and thank you very much guys for the fix
