### ISSUE TITLE
Project not getting synced when Status field is mapped in sheet

### ISSUE THREAD

**Issue by sanjayhvermak82** [Acumatica/Acumatica-Smartsheet#9]
Hi there,

I have mapped "Status" field in Template configuration. When I try to sync new project from Acumatica, I am getting an error.

Error: **_The value for cell in column 7419084883158916, D, did not conform to the strict requirements for type PICKLIST._**

Attached are screenshots for the same.

Could anyone help me to resolve this issue?

![Sheet Mapping](https://user-images.githubusercontent.com/101423448/157938035-32948d93-9ca0-4c92-a8ec-3c5a1f719e34.png)
![Status Sync Issue](https://user-images.githubusercontent.com/101423448/157938566-5b5b0905-042b-4cfe-aa7c-eea132fde5b7.png)

**Comment by sanjayhvermak82** [comment]
Hi @famadoz ,

Thank you for your response.

I am passing same value which Smartsheet is expecting "Not Started". However, it still give me error.

There should be mapping of status field with Smartsheet for complete PickList.

Please let me know your thoughts to move further.

**Comment by famadoz** [comment]
@sanjayhvermak82 
Does your Smartsheet field allow any values? For instance, if you try to enter "N" directly in Smartsheet, does it allow you to?

**Comment by sanjayhvermak82** [comment]
@famadoz 
Smartsheet has dropdown list. So "Not Started" has internal value of "N".

**Comment by famadoz** [comment]
@sanjayhvermak82 my impression is that this could be a conflict between the DB value and the UI value.
Please email me at famadoz@skyknack.com so that we can schedule a zoom and go over it live.

**Comment by famadoz** [comment]
@sanjayhvermak82 I am closing this issue as we have not received additional input.
If additional assistance is needed, please add a new entry
